### ISSUE TITLE
Options in Implementing this Extension

### ISSUE THREAD

**Issue by larry-tx** [cinghie/yii2-menu#2]
I am looking at using this extension in a number of my projects. Could you answer these questions:
1. Is it possible to install and use this extension without the multi-language extension? I would be using on the administrative backend of my site, and I have no need to the enormous and cumbersome overhead of supporting multiple languages that will never be used. This would be a show-stopper for me.
1. How can you associate an icon with menu entries?
1. Is it possible to do a vertical menu (left sidebar, for instance) as well as a horizontal menu (topnav, for instance)? How would you do that?
1. I assume that it is possible to style individual portions of the menu (background color, active menu item, for instance). Do you have a dictionary of the classes and elements used in the menus or do the conform to a standard, such as Bootstrap of Kartik's SideNav of NavX? If so what standard is used?
Thank you for your work on an extension that should have been a core part of Yii2 long ago.

**Comment by cinghie** [comment]
Hi @LarryTX,

1) yes you have only to set your language and nobody else

2) not now, it's a good idea i will implement it into a next version

3) not now, i will implement it into a next version

4) the options are the same of linkOptions array of an Nav item

https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.1/yii-bootstrap-nav#$items-detail
