### ISSUE TITLE
Setting unknown property: cinghie\menu\Menu::modelMap

### ISSUE THREAD

**Issue by larry-tx** [cinghie/yii2-menu#6]
Does your extension support modelMap? When it insert modelMap like the following it throws an error.
```
'menu'         => [
                'class'     => 'cinghie\menu\Menu',
                'menuRoles' => ['@'],
                'modelMap'  => [
                    'Items' => 'backend\themes\lel_admin\models\menu\items\Item'
                ],
            ],
```
I'm sure that all your custom traits are just wonderful for many folks, but they run contrary to many of the ways I do things. In addition, they require me to rummage around in the code to find out what they're doing. Consequently,  rather than using the ` <?= $model->getParentWidget($form,$model->getItemsSelect2()) ?>` widget, I'd much rather set up a normal relationship in the model as well as a function that builds and returns an array for it from the model. Hence I need to extend both the models.

Also, how do I get from your extension to the kind of data formatted as an ul/li list needed by Nav/Navbar/NavX? I can't seem to find an export mechanism to produce that.

**Comment by cinghie** [comment]
Implemented in last dev version
