### ISSUE TITLE
Trying to get property 'showTitles' of non-object

### ISSUE THREAD

**Issue by bmadeiro** [cinghie/yii2-menu#7]
Hello, 

after setting up the yii2-menu the error message of the title appeared. I think the system needs the module https://github.com/cinghie/yii2-essentials but I could not find it at this URL

<? if(Yii::$app->getModule('essentials')->showTitles): ?>
        <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    <?php endif ?>

**Comment by cinghie** [comment]
Hi @bmadeiro,
this bug was fixed some time ago on dev-master version.

Stable version will come as soon as possibile
